local   all             all                                     trust
host    all             all             0.0.0.0/0               scram-sha-256
host    replication     replicator      10.10.22.0/24           scram-sha-256
