FROM alpine:3.20

RUN apk add --no-cache \
    bind-tools \
    curl \
    iproute2 \
    iptables \
    iputils \
    netcat-openbsd \
    python3 \
    tcpdump \
    traceroute

CMD ["sleep", "infinity"]
