services:
  shell-1:
    build:
      context: chapters/05b-muliti-router/tools
    image: docker-networking-vpc-lab/chain-tools:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: ["sleep", "infinity"]
    networks:
      net_1:
        ipv4_address: 10.50.1.10

  shell-2:
    build:
      context: chapters/05b-muliti-router/tools
    image: docker-networking-vpc-lab/chain-tools:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: ["sleep", "infinity"]
    networks:
      net_2:
        ipv4_address: 10.50.2.10

  shell-3:
    build:
      context: chapters/05b-muliti-router/tools
    image: docker-networking-vpc-lab/chain-tools:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: ["sleep", "infinity"]
    networks:
      net_3:
        ipv4_address: 10.50.3.10

  shell-4:
    build:
      context: chapters/05b-muliti-router/tools
    image: docker-networking-vpc-lab/chain-tools:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: ["sleep", "infinity"]
    networks:
      net_4:
        ipv4_address: 10.50.4.10

  lab-router-1:
    build:
      context: chapters/05b-muliti-router/router
    image: docker-networking-vpc-lab/chain-router:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      net.ipv4.ip_forward: "1"
    command: ["sleep", "infinity"]
    networks:
      net_1:
        ipv4_address: 10.50.1.2
      net_2:
        ipv4_address: 10.50.2.2

  lab-router-2:
    build:
      context: chapters/05b-muliti-router/router
    image: docker-networking-vpc-lab/chain-router:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      net.ipv4.ip_forward: "1"
    command: ["sleep", "infinity"]
    networks:
      net_2:
        ipv4_address: 10.50.2.3
      net_3:
        ipv4_address: 10.50.3.2

  lab-router-3:
    build:
      context: chapters/05b-muliti-router/router
    image: docker-networking-vpc-lab/chain-router:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      net.ipv4.ip_forward: "1"
    command: ["sleep", "infinity"]
    networks:
      net_3:
        ipv4_address: 10.50.3.3
      net_4:
        ipv4_address: 10.50.4.2

networks:
  net_1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.50.1.0/24
          gateway: 10.50.1.1

  net_2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.50.2.0/24
          gateway: 10.50.2.1

  net_3:
    driver: bridge
    ipam:
      config:
        - subnet: 10.50.3.0/24
          gateway: 10.50.3.1

  net_4:
    driver: bridge
    ipam:
      config:
        - subnet: 10.50.4.0/24
          gateway: 10.50.4.1
